services:
  database:
    container_name: database
    image: postgres:16.0
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file:
      - .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

volumes:
  pgdata:
